[package]
name = "tempo-reliability"
description = "Acknowledgements, delivery channels and fragmentation for tempo."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
publish = false

[dependencies]
tempo-transport.workspace = true

[lints]
workspace = true
